services:
  postgres:
    image: postgres:15
    container_name: chat_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: chatdb
      TZ: "Asia/Ho_Chi_Minh"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  postgres_data:
