version: "3.9"

services:
  server:
    build:
      context: .
    container_name: chat_server
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://chatuser:123456@chat_postgres:5432/chatdb?schema=public"
      JWT_SECRET: "supersecret"
      PORT: 6112
    ports:
      - "6112:6112"
    networks:
      - chat_net

networks:
  chat_net:
    external: true